name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Nim
      run: |
        wget https://codeberg.org/janAkali/grabnim/raw/branch/master/misc/install.sh
        sh install.sh
        export PATH="$HOME/.nimble/bin:$PATH"
        export PATH="$HOME/.local/share/grabnim/current/bin:$PATH"

        for i in {1..3}; do
          grabnim 2.2.x || [ $? -eq 1 ] || break
          [ $i -eq 3 ] || sleep 5
        done

        echo "$HOME/.local/share/grabnim/current/bin" >> $GITHUB_PATH
        echo "$HOME/.nimble/bin" >> $GITHUB_PATH

    - name: Install Atlas
      run: |
        nim --version
        git clone https://github.com/nim-lang/atlas.git
        cd atlas
        nim buildRelease
        cd ../

    - name: Install dependencies
      run: ./atlas/atlas install --feature:test

    - name: Run tests
      run: nim test
