name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nim-version: ['stable']
        exclude:
          # Exclude some combinations to reduce CI time
          - os: windows-latest
            nim-version: devel
          - os: macos-latest
            nim-version: devel

    steps:
    - uses: actions/checkout@v4

    - name: Setup Nim
      run: |
        wget https://codeberg.org/janAkali/grabnim/raw/branch/master/misc/install.sh
        sh install.sh
        echo "$HOME/.local/share/grabnim/current/bin" >> $GITHUB_PATH
        echo "$HOME/.nimble/bin" >> $GITHUB_PATH

    - name: Install Atlas
      run: |
        nim --version
        git clone https://github.com/nim-lang/atlas.git
        cd atlas
        nim buildRelease
        cd ../

    - name: Install dependencies
      run: ./atlas/atlas install --feature:test

    - name: Run tests
      run: nim test
